/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgeVerificationInterface extends Interface {
  getFunction(
    nameOrSignature: "canAccess" | "isVerified" | "verifyAge"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AgeVerified"): EventFragment;

  encodeFunctionData(
    functionFragment: "canAccess",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifyAge", values?: undefined): string;

  decodeFunctionResult(functionFragment: "canAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyAge", data: BytesLike): Result;
}

export namespace AgeVerifiedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgeVerification extends BaseContract {
  connect(runner?: ContractRunner | null): AgeVerification;
  waitForDeployment(): Promise<this>;

  interface: AgeVerificationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canAccess: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  isVerified: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyAge: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canAccess"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyAge"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "AgeVerified"
  ): TypedContractEvent<
    AgeVerifiedEvent.InputTuple,
    AgeVerifiedEvent.OutputTuple,
    AgeVerifiedEvent.OutputObject
  >;

  filters: {
    "AgeVerified(address)": TypedContractEvent<
      AgeVerifiedEvent.InputTuple,
      AgeVerifiedEvent.OutputTuple,
      AgeVerifiedEvent.OutputObject
    >;
    AgeVerified: TypedContractEvent<
      AgeVerifiedEvent.InputTuple,
      AgeVerifiedEvent.OutputTuple,
      AgeVerifiedEvent.OutputObject
    >;
  };
}
