/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PassionToken } from "./PassionToken";
export * as factories from "./factories";
export { PassionToken__factory } from "./factories/PassionToken__factory";
