/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SessionModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeSessions"
      | "canAccess"
      | "configs"
      | "endSession"
      | "execute"
      | "initialize"
      | "startSession"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "activeSessions",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canAccess",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "endSession",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "startSession",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeSessions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canAccess", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "configs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endSession", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startSession",
    data: BytesLike
  ): Result;
}

export interface SessionModule extends BaseContract {
  connect(runner?: ContractRunner | null): SessionModule;
  waitForDeployment(): Promise<this>;

  interface: SessionModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeSessions: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { startTime: bigint; accumulatedCost: bigint }],
    "view"
  >;

  canAccess: TypedContractMethod<
    [contentId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  configs: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string] & { pricePerSecond: bigint; paymentToken: string }],
    "view"
  >;

  endSession: TypedContractMethod<
    [contentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [void],
    "payable"
  >;

  initialize: TypedContractMethod<
    [contentId: BigNumberish, arg1: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;

  startSession: TypedContractMethod<
    [contentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeSessions"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, bigint] & { startTime: bigint; accumulatedCost: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "canAccess"
  ): TypedContractMethod<
    [contentId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "configs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, string] & { pricePerSecond: bigint; paymentToken: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "endSession"
  ): TypedContractMethod<[contentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [contentId: BigNumberish, arg1: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startSession"
  ): TypedContractMethod<[contentId: BigNumberish], [void], "nonpayable">;

  filters: {};
}
