/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TipJarInterface extends Interface {
  getFunction(nameOrSignature: "creatorRegistry" | "tip"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Tipped"): EventFragment;

  encodeFunctionData(
    functionFragment: "creatorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tip", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "creatorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tip", data: BytesLike): Result;
}

export namespace TippedEvent {
  export type InputTuple = [
    creatorId: BigNumberish,
    from: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [creatorId: bigint, from: string, amount: bigint];
  export interface OutputObject {
    creatorId: bigint;
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TipJar extends BaseContract {
  connect(runner?: ContractRunner | null): TipJar;
  waitForDeployment(): Promise<this>;

  interface: TipJarInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  creatorRegistry: TypedContractMethod<[], [string], "view">;

  tip: TypedContractMethod<[creatorId: BigNumberish], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "creatorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tip"
  ): TypedContractMethod<[creatorId: BigNumberish], [void], "payable">;

  getEvent(
    key: "Tipped"
  ): TypedContractEvent<
    TippedEvent.InputTuple,
    TippedEvent.OutputTuple,
    TippedEvent.OutputObject
  >;

  filters: {
    "Tipped(uint256,address,uint256)": TypedContractEvent<
      TippedEvent.InputTuple,
      TippedEvent.OutputTuple,
      TippedEvent.OutputObject
    >;
    Tipped: TypedContractEvent<
      TippedEvent.InputTuple,
      TippedEvent.OutputTuple,
      TippedEvent.OutputObject
    >;
  };
}
